force-app/main/default/objects/Zip_Code__c/Zip_Code__c.object-meta.xml
<CustomObject>
    <label>Zip Code</label>
    <nameField>
        <label>Zip Code Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Zip_Code__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bulgaria</label>
            </value>
            <value>
                <fullName>BR</fullName>
                <label>Brazil</label>
            </value>
            <value>
                <fullName>CA</fullName>
                <label>Canada</label>
            </value>
            <value>
                <fullName>CH</fullName>
                <label>Switzerland</label>
            </value>
            <value>
                <fullName>CZ</fullName>
                <label>Czech Republic</label>
            </value>
            <value>
                <fullName>DE</fullName>
                <label>Germany</label>
            </value>
            <value>
                <fullName>DK</fullName>
                <label>Denmark</label>
            </value>
            <value>
                <fullName>DO</fullName>
                <label>Dominican Republic</label>
            </value>
            <value>
                <fullName>ES</fullName>
                <label>Spain</label>
            </value>
            <value>
                <fullName>FI</fullName>
                <label>Finland</label>
            </value>
            <value>
                <fullName>FO</fullName>
                <label>Faroe Islands</label>
            </value>
            <value>
                <fullName>FR</fullName>
                <label>France</label>
            </value>
            <value>
                <fullName>GB</fullName>
                <label>Great Britain</label>
            </value>
            <value>
                <fullName>GF</fullName>
                <label>French Guyana</label>
            </value>
            <value>
                <fullName>GG</fullName>
                <label>Guernsey</label>
            </value>
            <value>
                <fullName>GL</fullName>
                <label>Greenland</label>
            </value>
            <value>
                <fullName>GP</fullName>
                <label>Guadeloupe</label>
            </value>
            <value>
                <fullName>GT</fullName>
                <label>Guatemala</label>
            </value>
            <value>
                <fullName>GU</fullName>
                <label>Guam</label>
            </value>
            <value>
                <fullName>GY</fullName>
                <label>Guyana</label>
            </value>
            <value>
                <fullName>HR</fullName>
                <label>Croatia</label>
            </value>
            <value>
                <fullName>HU</fullName>
                <label>Hungary</label>
            </value>
            <value>
                <fullName>IM</fullName>
                <label>Isle of Man</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Zip_Code__c/fields/Places__c.field-meta.xml
<CustomField>
    <fullName>Places__c</fullName>
    <label>Places</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ZipCodeController.cls
/*
 * Controller to look for zip codes 
 *  
*/

public with sharing class ZipCodeController {

    @AuraEnabled(cacheable=true)
    public static Map<String,Object> getZipCodeData(String countryCode, String zipCode){
         Map<String,Object>responseWrapper = new Map<String,Object>();
        
        try {
            HttpRequest request = new HttpRequest();
            
            request.setEndpoint('https://api.zippopotam.us/' + countryCode + '/' + zipCode);
            request.setMethod('GET');
            request.setHeader('Accept', 'application/json');

            HttpResponse respoonse = new Http().send(request);
            String bodyJSON = respoonse.getBody();
            
            System.debug(bodyJSON);

            if ( bodyJSON.equals('{}') ){
                responseWrapper.put('status','warning');
                responseWrapper.put('message', 'Zip Code not found.');
                return responseWrapper;
            }
            
            Map<String, Object> mappedResponse = (Map<String, Object>) JSON.deserializeUntyped(bodyJSON);
            
            if ( mappedResponse.containsKey('country abbreviation') && mappedResponse.get('country abbreviation').equals('US')){
                responseWrapper.put('status','success');
                responseWrapper.put('data',bodyJSON);
            }else{
                upsertZipCode(bodyJSON);
                responseWrapper.put('status','success');
            }
        } catch (Exception e) {
            responseWrapper.put('status','error');
            responseWrapper.put('message', e.getMessage());
        }

        return responseWrapper;
    }


    @future
    public static void upsertZipCode(String bodyJSON){
        Map<String, Object> mappedResponse = (Map<String, Object>) JSON.deserializeUntyped(bodyJSON);
        Zip_Code__c zp = new Zip_Code__c();
        zp.Name = mappedResponse.get('post code').toString();
        zp.Country__c = mappedResponse.get('country abbreviation').toString();
        zp.Places__c = mappedResponse.get('places').toString();
        upsert zp Zip_Code__c.Name;
    }
}